apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest  
        imagePullPolicy: Never      
        ports:
        - containerPort: 50051      
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  - name: grpc
    port: 50051          
    targetPort: 50051    
    protocol: TCP
  type: ClusterIP        