apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  namespace: monitoring 
spec:
  selector:
    matchLabels:
      app: user-service 
  endpoints:
  - port: metrics 
    path: /metrics
    interval: 15s
    scheme: http