services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_currency_exchange
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml